version: '3.9'

services:

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: myapp-server
    container_name: myapp-node-server
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    # networks:
    #   - app-network
    # deploy:
    #   replicas: 3


  mongo:
    image: mongo
    volumes:
      - data-volume:/data/db
    ports:
      - "27018:27017"
    # networks:
    #   - app-network
    # deploy:
    #   replicas: 3


  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: myapp-client
    container_name: myapp-react-client
    depends_on:
      - server
    ports:
      - "80:80"
    # networks:
    #   - app-network
    # deploy:
    #   replicas: 3
    #   placement:
    #       constraints: [node.role == manager]

# networks:
#     app-network:
        # driver: bridge

volumes:
    data-volume:
